version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - ci
image: Visual Studio 2017
configuration: Release
platform: x64
shallow_clone: true
clone_folder: C:\openjdk
cache: C:\FreeType
nuget:
  disable_publish_on_pr: true
before_build:
- set
- dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\"
- cmd: echo "before build, would be here"
- ps: .\build.ps1
- DEL /F /Q C:\FT.tar C:\FT.tar.gz
- dir C:\freetype-2.8
- echo "Unfortunately, msys2_shell.cmd is quiet"
#- start /b C:\msys64\msys2_shell.cmd -c "touch /c/test.txt; echo test; exit; logout"
#- dir C:\
build:
  project: C:\openjdk\the.sln
  verbosity: minimal
test: off
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))