version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - ci
image: Visual Studio 2015
configuration: Release
platform: x64
shallow_clone: true
clone_folder: C:\openjdk
cache: C:\FreeType
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: XwTDukSNKnArn49FEtMm32fw3/qrN+iXUFAbhNa2bH8=
nuget:
  disable_publish_on_pr: true
before_build:
#- set
- ps: .\build.ps1
- DEL /F /Q C:\FT.tar C:\FT.tar.gz
- dir C:\freetype-2.8
- echo "Unfortunately, msys2_shell.cmd is quiet"
# because it spawns a new window where the output resides....
#- start /b C:\msys64\msys2_shell.cmd -c "touch /c/test.txt; echo test; exit; logout"
#"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2017\Visual Studio Tools\VC\x64 Native Tools Command Prompt for VS 2017.lnk"
#"%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: build.bat
build:
  project: C:\openjdk\the.sln
  verbosity: minimal
test: off
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))