version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - ci
image: Visual Studio 2017
configuration: Release
platform: x64
shallow_clone: true
clone_folder: C:\openjdk
cache: C:\FreeType
nuget:
  disable_publish_on_pr: true
before_build:
- dir C:\
- dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\"
- cmd: echo "before build, would be here"
build:
  project: C:\openjdk\the.sln
  verbosity: minimal
test: off
